name: Rebase, Push, and Close Merged PR

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - 'feature/**'  # Hoặc tên nhánh của bạn

jobs:
  rebase_and_push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout the code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Git
      - name: Set up Git
        run: |
          # Lấy tên và email từ GitHub actor (người kích hoạt workflow)
          GIT_USER_NAME=${{ github.actor }}  # Tên người kích hoạt
          GIT_USER_EMAIL="${{ github.actor }}@users.noreply.github.com"  # Email liên kết với GitHub

          # Cấu hình Git
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"

      # Bước 3: Rebase nhánh vào main (nếu là push hoặc PR đã merged)
      - name: Rebase with main
        run: |
          git fetch origin main
          git rebase origin/main
        continue-on-error: true  # Không dừng lại nếu có xung đột

      # Bước 4: Kiểm tra xung đột (conflict)
      - name: Check for rebase conflicts
        run: |
          if git diff --check | grep -q 'conflict'; then
            echo "There are merge conflicts, rebase failed!"
            exit 1  # Thất bại nếu có conflict
          fi

      # Bước 5: Nếu rebase thành công, push lên nhánh main
      - name: Push changes to main
        run: |
          git push origin HEAD:main
        if: success()  # Chỉ thực hiện nếu bước rebase thành công

  close_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: rebase_and_push  # Chạy sau khi rebase and push thành công

    steps:
      # Bước 6: Đóng Pull Request
      - name: Close merged pull request
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          echo "Closing pull request: #$PR_NUMBER"
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"state": "closed"}' \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER
